### ISSUE TITLE
Need image for card

### ISSUE THREAD

**Issue by dazzaji** [LegalMarkup/LegalMaterialDesign#1]
Caitlin - for our Think Sesh with Lloyd, can you share an image for StoreWell app project card?

**Comment by prhana** [comment]
My screen Shot ![screen shot 2015-06-14 at 8 24 35 pm](https://cloud.githubusercontent.com/assets/8837791/8151128/ae049f5a-12d2-11e5-84eb-23268d5e88fc.png)
